-- FIND DETAILS OF THOSE PATIENTS WHO HAVE ORDERED MEDICINES OF QUANTITY GREATER THAN 10
 
SELECT p.FIRST_NAME
,p.AGE ,
p.email FROM patient p
WHERE PID IN ( SELECT PID FROM bill 
where QUANTITY>10 );