-- UPDATE TABLE MEDICINES_DETAILS, DECREASE QUANTITY BY 5 
-- FROM ALL THOSE MEDICINES WHICH ARE PRESENT IN BILL AND HAVE QUANTITY 5 
UPDATE MEDICINE_DETAILS
SET QUANTITY = QUANTITY - 5
WHERE drug_id IN (
  SELECT drug_id
  FROM bill
  WHERE QUANTITY = 5
);

