-- FIND THE DETAILS OF THE MEDICINES(DRUG_ID ,MFG_DATE, EXP_DATE,SUPPLIER) WHICH ARE ORDERED (PRESENT IN THE BILL)

SELECT BILL.DRUG_ID AS ID, MEDICINE_DETAILS.MFG_DATE,
MEDICINE_DETAILS.EXPIRY_DATE,
MEDICINE_DETAILS.SUPPLIER
FROM MEDICINE_DETAILS
LEFT JOIN BILL
ON MEDICINE_DETAILS.DRUG_ID = BILL.DRUG_ID
ORDER BY EXPIRY_DATE;