-- UPDATE TABLE SALES_DETAIL, ADD 500 TO TOTAL_SALES  
-- IN MEDICINES PRESENT IN THE UPDATED BILL TOTAL PRICE IS 500  

UPDATE SALES_DETAILS
SET TOTAL_SALES = TOTAL_SALES + 500
WHERE ITEM_CODE IN (
  SELECT drug_id
  FROM bill
  WHERE TOTAL_PRICE = 500
);
