-- FIND NAME, EMIAL AND EMPLOYEE_ID OF THOSE EMPLOOYEE WHO ARE SALES EXECUTIVE AND HAVE ID BETWEEN 01 AND 30  
SELECT NAME, EMPLOYEE_ID, EMAIL_ID
FROM EMPLOYEE
WHERE (POSITION = "Sales Executive" OR POSITION = "CLERK")
AND 
(EMPLOYEE_ID BETWEEN 1 AND 30)
ORDER BY NAME;

  